.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. javabit_qt test_javabit_qt
clean: FORCE
	$(MAKE) -C .. javabit_qt_clean test_javabit_qt_clean
check: FORCE
	$(MAKE) -C .. test_javabit_qt_check
javabit-qt javabit-qt.exe: FORCE
	 $(MAKE) -C .. javabit_qt
